services:
  jenkins:
    image: jenkins-playwright
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home

volumes:
  jenkins-data:
    external: true